package mcnellen;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.io.IOException;

public class PrimeNumbers {
	
	static boolean[] primes = new boolean[10000];
	
	/**
	 * <h1>PrimeNumbers</h1>
	 * <p>Takes a series of integers from the user and returns if they are prime numbers</p>
	 * @author	Quinlan McNellen
	 * @date	2016/05/26
	 * @version	1.0.0
	 * @param	args
	 * @throws	IOException
	 */
	public static void main(String[] args) throws IOException {
		BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
		String[] tokens = in.readLine().split(" ");
		fillSieve();
		for (int i=0; i<tokens.length; i++) {
			System.out.println(isPrime(Integer.parseInt(tokens[i])));
		}
	}
	/**
	 * checks if 0-9999 (by default) are prime numbers
	 * <br>
	 * length depends on the length of the primes array
	 */
	public static void fillSieve() {
		Arrays.fill(primes, true);
		primes[0] = false; primes[1] = false;
		for (int i=2; i<primes.length; i++) {
			if (primes[i]) {
				for (int x=2; i*x<primes.length; x++) {
					primes[i*x] = false;
				}
			}
		}
	}
	/**
	 * references the array generated by fillSieve and checks if a number is prime
	 * @see	fillSieve()
	 * @param	n	number to check
	 * @return
	 */
	public static boolean isPrime(int n) {
		return primes[n];
	}
}
